name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
  MY_NAME_2:
    description: "Who to greet 2"
    required: true
    default: "World 2"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "red"
